#!/bin/bash

echo $(whoami)
# This script should be run as sudo, as it configures the initialiser launch options..

# Install the launchctl services.

launchctl load -w /Library/LaunchDaemons/com.sergiogallegos.macxlr.initialiser.mini.plist
launchctl load -w /Library/LaunchDaemons/com.sergiogallegos.macxlr.initialiser.full.plist

# And for good measure, we'll perform an initial run of the initialiser..
'/Library/Application Support/com.sergiogallegos.macxlr/goxlr-initialiser'
