#!/bin/bash

# This script configures the packaged MacXLR app to use the attached `goxlr-utility-ui` binary
# for configuration. This should be run as the User.
sudo -u $USER '/Applications/MacXLR.app/Contents/MacOS/goxlr-utility-ui' --install
